In [1]:
import sys
import numpy as np
import numpy.linalg as LA

## Tests of Random and Utils
- Generate a 3-dim'l random Gaussian distribution whose stds are upper bounded by 1.;
- Calculate the square root of its covariance matrix Sigma, denoted as Sigma_rt;
- Compare the eigenvalues of Sigma and those of Sigma_rt squared;

In [2]:
import Random
import Utils

In [3]:
mu, Sigma = Random.rand_Gaussian(3, 1.)
Sigma_rt = Utils.mat_sqrt(Sigma)
w, v = LA.eigh(Sigma)
print(w)
        
w_rt, v_rt = LA.eigh(Sigma_rt)
print(w_rt ** 2.)

[0.32003424 0.51406317 0.64824524]
[0.32003424 0.51406317 0.64824524]


## Tests for Hypergraph
- Hypergraph Laplacian
- Random-walk conditional probabilities
- Neighborhood distance matrix
- Shortest path distance matrix

In [4]:
import Hypergraph as hg
sys.path.append('../Data')
import Load_Hypergraph as lh
import Stochastic_Block_Model as SBM

### Toy examples

#### Simple graph

In [7]:
num_vertices = 5
edges = [[0, 2], [0, 3], [1, 3], [2, 4]]
Lap = hg.hypergraph_Laplacian(num_vertices, edges)
print('Laplacian of the graph (treated as hypergraph) =\n{}'.format(Lap))
print('We can see it equals a half of simple graph Laplacian.\n')

rw_conditional_probs = hg.hypergraph_random_walk(num_vertices, edges)
print('Random walk conditional probabilities\
of the graph (treated as hypergraph) =\n{}'.format(rw_conditional_probs))

lazyness = .3
rw_conditional_probs_l = hg.hypergraph_random_walk(num_vertices, edges, lazyness=lazyness)
print('Random walk conditional probabilities\
of the graph with lazyness {} =\n{}'.format(lazyness, rw_conditional_probs_l))

lazyness = 0
rw_conditional_probs_l = hg.hypergraph_random_walk(num_vertices, edges, lazyness=lazyness)
print('Random walk conditional probabilities\
of the graph with lazyness {} =\n{}\n'.format(lazyness, rw_conditional_probs_l))

nbh_distances, MAX = hg._neighborhood_distances(num_vertices, edges)
print('neighborhood distance matrix of the graph =\n{}'.format(nbh_distances))

connected, pw_distances = hg.pairwise_distances(num_vertices, edges)
print('pairwise distance matrix of the graph =\n{}'.format(pw_distances))

Laplacian of the graph (treated as hypergraph) =
[[ 0.5         0.         -0.25       -0.25        0.        ]
 [ 0.          0.5         0.         -0.35355339  0.        ]
 [-0.25        0.          0.5         0.         -0.35355339]
 [-0.25       -0.35355339  0.          0.5         0.        ]
 [ 0.          0.         -0.35355339  0.          0.5       ]]
We can see it equals a half of simple graph Laplacian.

Random walk conditional probabilitiesof the graph (treated as hypergraph) =
[[0.5  0.   0.25 0.25 0.  ]
 [0.   0.5  0.   0.5  0.  ]
 [0.25 0.   0.5  0.   0.25]
 [0.25 0.25 0.   0.5  0.  ]
 [0.   0.   0.5  0.   0.5 ]]
Random walk conditional probabilitiesof the graph with lazyness 0.3 =
[[0.3  0.   0.35 0.35 0.  ]
 [0.   0.3  0.   0.7  0.  ]
 [0.35 0.   0.3  0.   0.35]
 [0.35 0.35 0.   0.3  0.  ]
 [0.   0.   0.7  0.   0.3 ]]
Random walk conditional probabilitiesof the graph with lazyness 0 =
[[0.  0.  0.5 0.5 0. ]
 [0.  0.  0.  1.  0. ]
 [0.5 0.  0.  0.  0.5]
 [0.5 0.5 0.  

#### Hypergraph

### Example with stochastic block model

In [5]:
num_vertices = 30
communities = SBM.generate_random_communities(num_vertices, num_communities=2)
p_1, p_2 = .05, .01
edges = SBM.stochastic_block_model(communities, 3, [p_1, p_2])
vertices = lh._get_vertices(num_vertices, edges)
print('number of edges = {}'.format(len(edges)))
for i, vertex in enumerate(vertices):
    print('{}:\t{}'.format(i, vertex))

number of edges = 78
0:	[0, 1, 2, 3, 4, 5, 6, 7]
1:	[8, 9, 10, 11, 12]
2:	[0, 1, 2, 13, 14, 15, 16, 17, 18, 19]
3:	[8, 13, 14, 20, 21, 22]
4:	[15, 23, 24, 25, 26, 27, 28, 29]
5:	[9, 30, 31, 32, 33]
6:	[3, 9, 34]
7:	[0, 16, 30, 35, 36, 37]
8:	[4, 10, 13, 17, 31, 38, 39, 40]
9:	[8, 20, 32, 35, 38, 41, 42, 43, 44, 45]
10:	[5, 20, 23, 24, 41, 46]
11:	[1, 5, 11, 18, 21, 25, 42]
12:	[6, 17, 26, 31, 32, 39, 43, 47]
13:	[23, 27, 34, 36, 48, 49]
14:	[2, 10, 11, 16, 26, 38, 39, 47, 50, 51]
15:	[22, 33, 48, 50, 52, 53, 54, 55]
16:	[24, 41, 43, 44, 56, 57, 58, 59, 60, 61, 62]
17:	[51, 63, 64]
18:	[7, 18, 19, 28, 52, 56, 57, 63, 65]
19:	[12, 25, 37, 40, 50, 58, 66, 67, 68]
20:	[28, 42, 46, 49, 69, 70, 71, 72]
21:	[34, 59, 60, 64, 66]
22:	[6, 14, 15, 22, 53, 56, 59, 69, 73, 74]
23:	[3, 19, 21, 37, 61, 70]
24:	[7, 27, 29, 33, 44, 45, 46, 53, 54, 69, 70, 73, 75]
25:	[12, 36, 45, 51, 52, 55, 57, 65, 71, 75, 76]
26:	[49, 54, 60, 62, 67, 68, 71, 72, 74, 76]
27:	[40, 48, 63, 65, 66, 67, 72, 76, 77]
28:	[4

In [6]:
Laplacian = hg.hypergraph_Laplacian(num_vertices, edges)
print(Laplacian)

[[ 0.66666667  0.         -0.1118034   0.          0.          0.
  -0.06804138 -0.04811252 -0.04166667  0.         -0.04811252 -0.08908708
  -0.04166667  0.         -0.0372678   0.          0.          0.
  -0.03928371  0.          0.          0.         -0.0372678  -0.04811252
  -0.03268602  0.          0.          0.         -0.04166667  0.        ]
 [ 0.          0.66666667  0.         -0.06085806  0.         -0.06666667
  -0.0860663   0.         -0.05270463 -0.04714045  0.         -0.05634362
   0.          0.         -0.0942809   0.          0.          0.
   0.         -0.0496904   0.          0.          0.          0.
   0.         -0.04494666  0.          0.          0.          0.        ]
 [-0.1118034   0.          0.66666667 -0.0860663  -0.0372678   0.
   0.         -0.0860663  -0.0745356   0.          0.         -0.07968191
  -0.0372678   0.         -0.06666667  0.          0.          0.
  -0.07027284  0.          0.          0.         -0.06666667 -0.04303315
   0.     